### ISSUE TITLE
Sonoma

### ISSUE THREAD

**Issue by ejh4286** [ryanilano/hackintosh-asus-b650ef-amd#1]
Will there be an update of the EFI for Sonoma

**Comment by ryanilano** [comment]
Yes. Apple has dropped support for the Broadcom drivers so I've been hesitant to update since I really like Continuity. I will update once Sonoma has been released.

**Comment by ryanilano** [comment]
OCLP is getting closer but I'm still not upgrading until its 100% or until I absolutely have to
