### ISSUE TITLE
Downgrade UEFI?

### ISSUE THREAD

**Issue by mmaster23** [ryanilano/hackintosh-asus-b650ef-amd#3]
Hi, I found your repo and I have the same board. I'm having issues getting past [EB|#LOG:EXITBS:START] and tried multiple solutions mentioned in the OpenCore Guide and several forum. When looking at your notes, you're saying the UEFI version matters and you're having issues with 1807. I'm trying to downgrade to 1654 but it won't let me via EZ Flash 3. How did you downgrade to lower version? It keeps whining about setting the downgrade setting but I've toggled that multiple times now and has zero effect.

Trying to run Sonoma btw.
cc: @ryanilano

**Comment by ryanilano** [comment]
I don't know about Sonoma but I do have the fixes to run opencore in the[ 0.9.9](https://github.com/ryanilano/hackintosh-asus-b650ef-amd/releases/tag/0.9.9) release
