### ISSUE TITLE
Can the efi be used for R5-7500f and how did you made the motherboard mmio

### ISSUE THREAD

**Issue by MioneRyu** [ryanilano/hackintosh-asus-b650ef-amd#4]
My motherboard is ROG B650e-f too, but my cpu is 7500f. I hear from every am5 motherboard needs to make the unique mmio. How did you make the mmio? Thank you

**Comment by ryanilano** [comment]
not 100% sure. try asking in amd-osx.com

**Comment by MioneRyu** [comment]
I have used your efi file that successed to boot the Ventura. I encountered a problem what I can't disable my Nvidia gpu. I found some content in the DeviceProperties column. I tried to modify some pci contents that it will be failed to boot macOS. Because I am not sure the role of these contents and suitable for my pc, can you tell me the pci contents what is the role they play? Thank you.
![截屏2024-06-29 18 53 02](https://github.com/ryanilano/hackintosh-asus-b650ef-amd/assets/130836848/06cf4bc5-d49c-4a17-8135-53b792fb8c7d)
