### ISSUE TITLE
B650E-F w. BIOS v.3056

### ISSUE THREAD

**Issue by InfiniteBSOD** [ryanilano/hackintosh-asus-b650ef-amd#5]
Hello,

Really glad I found your repo, I have  the following specs:
AMD Ryzen 7 7800X3D (8C/(16T)
2*16GB Kingston Fury  DDR5-6000
PowerColor RX 7800 XT
Samsung SSD 990 PRO 1TB
Fractal Design North (just as you 👍)

I am however on BIOS 3056 and tried to downgrade to 1654 but my BIOS doesn't accept the (renamed) 1654 as a valid BIOS-file.
And yes, I have enabled BIOS flashback.

I tried booting into the OS X installer and it just loops indefinitely.
I will enable logging to file to be able to save the output and troubleshoot further but I just wanted to ask if you could share your BIOS settings?

I have disabled IMMOU  but that is about it, I have probably missed something.
I went into Advanced and then saved my BIOS settings to a USB-drive which makes it to a .txt and was thinking if I could bother you to do the same and then I could just diff both files and see the changes and if something that is different is something I should change.

My BIOS-settings (exported through the BIOS > Advanced > Save profile > Save to USB (something like that):
https://pastebin.com/vrAZsAkm

Best Regards

**Comment by ryanilano** [comment]
I looked at your BIOS pretty quickly and didn't see anything weird.The BIOS is probably no the issue -- I think [AM5-ASUS-B650EF-BIOS-Fix-DSDT.aml](https://github.com/ryanilano/hackintosh-asus-b650ef-amd/blob/master/EFI/OC/ACPI/AM5-ASUS-B650EF-BIOS-Fix-DSDT.aml) takes care of microcode updates that came along with the 9000 series chipsets.

> PowerColor RX 7800 XT
This graphics card is not supported and is a problem you won't be able to get around. The Navi 21 (6800/XT, 6900, 6950)  series is the newest generation supported natively. Certain AMD APUs are supported with NootedRed but the iGPU in the 7800X3D isn't the same as the APUs. 

You have two options: 
1. You probably won't like this -- replace your 7800XT with a supported card (6950XT would be the high end option)
2. if your PSU/North allows install a second GPU, You can pick up RX 580 8GB for under a hundred dollars or a 5700 XT for 150$. You can leave two GPUs in and use one for windows and one for open core.

I'd suggest checking out amd-osx forums. It's a really helpful community.

**Comment by InfiniteBSOD** [comment]
> I looked at your BIOS pretty quickly and didn't see anything weird.The BIOS is probably no the issue -- I think [AM5-ASUS-B650EF-BIOS-Fix-DSDT.aml](https://github.com/ryanilano/hackintosh-asus-b650ef-amd/blob/master/EFI/OC/ACPI/AM5-ASUS-B650EF-BIOS-Fix-DSDT.aml) takes care of microcode updates that came along with the 9000 series chipsets.
> 
> > PowerColor RX 7800 XT
> > This graphics card is not supported and is a problem you won't be able to get around. The Navi 21 (6800/XT, 6900, 6950)  series is the newest generation supported natively. Certain AMD APUs are supported with NootedRed but the iGPU in the 7800X3D isn't the same as the APUs.
> 
> You have two options:
> 
> 1. You probably won't like this -- replace your 7800XT with a supported card (6950XT would be the high end option)
> 2. if your PSU/North allows install a second GPU, You can pick up RX 580 8GB for under a hundred dollars or a 5700 XT for 150$. You can leave two GPUs in and use one for windows and one for open core.
> 
> I'd suggest checking out amd-osx forums. It's a really helpful community.

Appreciate your reply.

Knew about the GPU but was hoping that "not supported" would mean that I couldn't utilize the performance of the GPU but would still receive a signal (be able to use the desktop etc.).

I have an Alder Lake laptop which I've seen some promising posts for (for Alder Lake) in regards to running OpenCore, think I'll try running OpenCore on my laptop instead.

Once again - cheers for your repo and sharing your config and also for responding.
